### ISSUE TITLE
Songbird doesn't clean zombie processes (ffmpeg & youtube-dl)

### ISSUE THREAD

**Issue by vilgotf** [serenity-rs/songbird#38] opened 2021-01-23 10:13 UTC

**Comment by FelixMcFelix** [comment] 2021-01-23 10:36
Hi, can you please expand? What OS are you running on, what steps cause zombie processes? I don't encounter this behaviour on Windows.

**Comment by vilgotf** [comment] 2021-01-23 11:06
Using `Restartable::ytdl` and `Restartable::ytdl_search` (but presumably every call to ytdl) (and then `play_source()`) *always* produces zombie processes (calling `.stop()` or waiting for the video to run out) on Linux.
I'm also using twilight, not serenity

**Comment by JellyWX** [comment] 2021-01-26 16:26
+1, running on Linux using `create_player` to produce tracks leaves behind hundreds of zombies. Using serenity

**Comment by FelixMcFelix** [comment] 2021-01-26 17:16
Process handling is pretty OS-specific. I suspect Linux also requires `wait` rather than just kill, so it's a bit behind Windows in this regard.

This might need us to add a graveyard thread to dispose of processes/resources: for instance, I don't think it'd be a good idea to `wait` on a manually stopped track (which could then require finishing a 10s of MB download, in the worst case). Maybe SIGINT + `wait` on another thread will suffice. This should be doable in a reusable way (i.e., for all `Input` types), and I'm sure it can be done without breaking semver.

**Comment by peppizza** [comment] 2021-01-29 20:28
It does not seem like this issue is fixed.  On my linux VM songbird still does not clean up zombie processes even after updating.

**Comment by JellyWX** [comment] 2021-01-29 20:34
It seems resolved for me, although I still have a 'cpu leak' as I'll call it where the usage climbs continuously through runtime

-------- Original Message --------

**Comment by peppizza** [comment] 2021-01-29 21:49
On my machine, even after a song ends or is stopped, the youtube-dl and ffmpeg processes are still running through monitoring via htop

**Comment by FelixMcFelix** [comment] 2021-01-29 22:16
Peppizza, can you please specify your OS, or provide any code samples? I cannot reproduce this. I am not seeing this on Ubuntu 20 (kernel 5.8.0), using both ytdl sources and ffmpeg chained into `Compressed`.

**Comment by peppizza** [comment] 2021-01-29 22:43
I am using Ubuntu 20.10 with kernel 5.8.0-41-generic, and it occurs when using Restartable::ytdl or Restartable::ytdl_search

**Comment by FelixMcFelix** [comment] 2021-01-31 13:02
@peppizza Could you please try seeing what modifying the [unix-specific drop behaviour](https://github.com/serenity-rs/songbird/blob/current/src/input/child.rs#L43-L49) does for your setup? Test out first using the local repo exactly to rule out old versioning, add a print to see whether the unix branch is being skipped, try waiting without signalling, different signals, etc.

SIGINT -> wait should be the best way to cleanup the process without forcibly working through the rest of the download + decode pipeline, but tell me what you find.

**Comment by FelixMcFelix** [comment] 2021-02-01 01:18
Reopening: it seems that the wait doesn't terminate in a reasonable time frame, and dropping a Child process in an async context will block that thread. This seems to need some more work,

**Comment by peppizza** [comment] 2021-02-01 02:23
Is there any reason you spawn a std thread instead of a tokio thread?

**Comment by FelixMcFelix** [comment] 2021-02-01 09:35
Yes: due to both ergonomics of Read/Seek vs AsyncRead/AsyncSeek, and performance.

On the first point, I wanted to make additional extensions (for the library itself and external audio sources) easy to develop. On the latter, we were seeing in preliminary testing that enough audio mixers would choke up async threads (particularly as encryption blocks for ~1ms and contains no yield points), and that mixing would actually be slower async. I plotted some rough measurements [here](https://github.com/serenity-rs/serenity/pull/806#issuecomment-688335757).

EDIT: Disposal thread is std so that it *should* be safer to wait/drain finished processes built with the synchronous Read api.

**Comment by FelixMcFelix** [comment] 2021-02-01 13:45
Could anyone suffering from this please try the [zombies branch](https://github.com/serenity-rs/songbird/tree/zombies) from the git repo, and tell me how you get on with zombie processes/CPU utilisation/etc.?

**Comment by peppizza** [comment] 2021-02-02 02:30
For me at least, the zombies branch cleans up zombie processes, I don't have any info about cpu utilization

**Comment by FelixMcFelix** [comment] 2021-02-02 18:53
Going to close this for now, since `zombies` has been merged in to decent feedback from several users. I'll push this to crates once tokio 0.2 back-compat is merged in. I hope that this issue does not rise again! 🧟

**Closed as completed by FelixMcFelix** 2021-02-02 18:53 UTC
Labels: bug, driver
